:concurrency: 5
:queues:
  - default
  - backups
  - metrics
  - mailers
  - newsletter
  - events
  - scheduled

:scheduler:
  :schedule:
    CalculateAllMetrics:
      cron: '0 0 0 * * *' # Run at midnight
      class: CalculateAllMetricsJob
      queue: scheduled
    OrdersReminder:
      cron: '0 0 18 * * *' # Run at 18:00
      class: OrdersReminderJob
      queue: scheduled
    PreloadOpenData:
      cron: '0 0 1 * * *' # Run at 01:00
      class: PreloadOpenDataJob
      queue: scheduled

